/**
 * C — The six-dimension analysis (§7.3). For each dimension: what we see →
 * what it costs → what decision it points to.
 */

import type { MaterialSection } from "@/lib/materialSection";
import type { MaterialSectionId } from "../sections";

export type DimensionId = "network" | "iot" | "fiveg" | "data" | "complexity" | "governance";

export type Dimension = {
  id: DimensionId;
  n: number;
  label: string;
  whatWeSee: string;
  whatItCosts: string;
  decisionItPointsTo: string;
  /** Illustrative exposure rating, 0–100, for the heat strip. Not measured data. */
  exposure: number;
};

export const DIMENSIONS: Dimension[] = [
  {
    id: "network",
    n: 1,
    label: "Network energy efficiency",
    whatWeSee:
      "A partly inefficient estate with no load-flexible operation — links and access points running near full-load power regardless of demand, the same pattern the 3G evidence from GSMA describes at operator scale (about a third of mobile network energy for well under 1% of data traffic).",
    whatItCosts:
      "A baseline that grows every time new equipment is added on top of it, and a modernisation programme that becomes larger and more disruptive the longer retirement of the old layer is deferred.",
    decisionItPointsTo: "Which parts of the network actually need modernising, targeted rather than estate-wide, and a stated retirement date for what they replace.",
    exposure: 70,
  },
  {
    id: "iot",
    n: 2,
    label: "IoT lifecycle",
    whatWeSee:
      "Devices with mixed energy and maintenance profiles, planned without shared criteria — the embodied-impact-dominance pattern for small devices, where manufacturing footprint frequently exceeds lifetime operational consumption.",
    whatItCosts:
      "A support-period problem under WEEE and the emerging ESPR obligations: a device without a defined support commitment, under the same logic ETSI EN 303 645 and the Cyber Resilience Act apply to security, becomes a forced early replacement rather than a planned one.",
    decisionItPointsTo: "Lifecycle criteria applied at procurement — power supply, support period, end-of-life route — before the next device order, not after the fleet exists.",
    exposure: 65,
  },
  {
    id: "fiveg",
    n: 3,
    label: "5G benefit",
    whatWeSee:
      "Several proposed use cases, most without an evidenced throughput, latency, density or mobility requirement that existing connectivity cannot already meet.",
    whatItCosts:
      "The per-bit efficiency target the specification promises has nothing to say about total consumption once four use cases run instead of one — layer stacking and rebound both apply, and neither is fixed by better radio hardware.",
    decisionItPointsTo: "A qualifier applied to every candidate use case before deployment: which requirement is real, and evidenced, not assumed.",
    exposure: 55,
  },
  {
    id: "data",
    n: 4,
    label: "Data strategy",
    whatWeSee:
      "Data streams and analysis logics with no documented priority or owner, generated by devices and radios that were each approved on their own terms.",
    whatItCosts:
      "A downstream cost that lands in the analytics platform's budget rather than the requesting department's — scope displacement in its clearest form, which is exactly why nobody currently feels the cost of the decision that caused it.",
    decisionItPointsTo: "An owner named for every data stream at the point it is created, with the question 'which decision does this feed' answered before collection starts.",
    exposure: 50,
  },
  {
    id: "complexity",
    n: 5,
    label: "Operational complexity",
    whatWeSee:
      "Every additional system — gateway, edge node, management console — arriving with its own monitoring, spares, required skills and failure modes, none of it named in the business case that approved the underlying device or link.",
    whatItCosts:
      "The cost line that never appears in a proposal but always appears in an operations budget a year later: complexity overhead compounds with every subsequent decision made under the same conditions.",
    decisionItPointsTo: "Counting complexity cost explicitly in every proposal, as a named line, not an assumed absorption into existing operations capacity.",
    exposure: 60,
  },
  {
    id: "governance",
    n: 6,
    label: "Governance",
    whatWeSee:
      "No binding criteria at all for device selection, lifecycle management or sustainability assessment — the absence that lets every other dimension above recur, unconstrained.",
    whatItCosts:
      "The point of maximum leverage, left unused: an approval gate is where a decision could still be refused, and NetSphere currently has none for connectivity investment.",
    decisionItPointsTo: "Who owns the measurement, who can bind capacity to it, and what the gate actually tests against — the governance and architecture framework the rest of this route builds toward.",
    exposure: 85,
  },
];

export const dimensionById = (id: DimensionId) => DIMENSIONS.find((d) => d.id === id)!;

export const HEAT_STRIP_LEGEND = "Exposure ratings are the case author's analytical judgement, not measured data.";

// ---------------------------------------------------------------------------
// The section
// ---------------------------------------------------------------------------

export const C_DIMENSIONS: MaterialSection<MaterialSectionId> = {
  id: "dimensions",
  code: "C",
  n: 3,
  icon: "target",
  kicker: "C · What we see, what it costs, what it points to",
  title: "The six-dimension analysis",
  standfirst: "Every hotspot from section B lands in exactly one of six dimensions. Governance is where the other five compound.",
  minutes: 18,
  definition:
    "Six dimensions cover NetSphere's full exposure: network energy efficiency, IoT lifecycle, 5G benefit, data strategy, operational complexity, and governance. Each is analysed the same way — what we see, what it costs, what decision it points to — so the six read as one connected argument rather than six separate technology reviews.",
  insight:
    "Governance is not one dimension among six equals. It rates highest on the heat strip because it is the dimension whose absence lets the other five recur without limit — a network modernisation done once, an IoT fleet selected once and a 5G use case qualified once are each single decisions, but the absence of binding criteria reproduces the same errors in every decision NetSphere makes after this one.",
  takeaway:
    "Do not treat the six as independent findings to fix one at a time. Network, IoT and 5G decisions all feed the same data and complexity consequences, and all five of them are only made once, correctly, if governance criteria exist before the next one is approved. That is the logic section D's levers, and section E's prioritised measure, both build on directly.",
  body: [
    {
      heading: "Why network, IoT and 5G share one root cause",
      paragraphs: [
        "Read consecutively, dimensions one through three describe the same pattern in three technologies: capacity provisioned without a load-flexibility or evidenced-requirement test, and no retirement obligation attached to what it replaces or duplicates. Fixing any one of the three without fixing the shared cause — the missing criteria in dimension six — produces a correct decision this quarter and no defence against the same mistake next quarter.",
      ],
    },
    {
      heading: "Data and complexity as consequences, not causes",
      paragraphs: [
        "Dimensions four and five are downstream of the first three. Unprioritised data streams and uncounted operational complexity are not separate technology problems NetSphere happens to also have; they are what network, IoT and 5G decisions produce when nothing requires their consequences to be named at the point of approval.",
      ],
    },
  ],
  reasoning: [
    "When you analyse Vertex in the task, sort its facts by these same six dimensions before you decide which lever to pull — a fact that looks like a technology problem (an uneven network estate, an unqualified 5G use case) is still analysed the same way: what we see, what it costs, what decision it points to.",
    "Governance rating highest here is the reason section E's prioritised measure for NetSphere is a governance framework, not a network upgrade — check whether the same logic transfers to Vertex, or whether Vertex's specific conditions change which dimension is most acute.",
  ],
  callout: {
    label: "The one-sentence version",
    text: "Network, IoT and 5G are where the decisions are made. Data and complexity are where their consequences land. Governance is what would have stopped the same mistake happening twice.",
  },
  references: [
    {
      label: "WEEE Directive 2012/19/EU; ESPR (EU) 2024/1781",
      detail: "Collection, treatment and producer-responsibility obligations; durability, reparability, recyclability and the Digital Product Passport.",
    },
    {
      label: "ETSI EN 303 645; EU Cyber Resilience Act",
      detail: "Consumer IoT security baseline and support-period obligations behind the lifecycle-criteria argument.",
    },
    {
      label: "ISO/IEC 30141:2018 — IoT Reference Architecture",
      detail: "Device, gateway, network, platform and application tiers — the vocabulary for where complexity actually accumulates.",
    },
  ],
};
