/**
 * D — The four biggest levers (§7.4), presented as a self-paced accordion.
 */

import type { MaterialSection } from "@/lib/materialSection";
import type { MaterialSectionId } from "../sections";

export type BigLever = {
  id: string;
  n: number;
  label: string;
  changes: string;
  requires: string;
  doesNotFix: string;
  measurement: string;
};

export const BIG_LEVERS: BigLever[] = [
  {
    id: "framework",
    n: 1,
    label: "Introduce an architecture and governance framework for connected infrastructure",
    changes: "What counts as an approvable network, IoT or 5G decision — binding criteria for benefit, energy demand and lifecycle, tested at a real approval gate.",
    requires: "A named owner who can bind capacity to it, and the authority to refuse a proposal that fails the criteria.",
    doesNotFix: "Anything already deployed. It governs what happens next, not the estate as it stands today.",
    measurement: "The share of new connectivity proposals that were refused or amended at the gate — zero refusals after a year means the framework is decorative.",
  },
  {
    id: "network",
    n: 2,
    label: "Modernise the most inefficient parts of the network",
    changes: "Baseline power on the specific links and sites the six-dimension analysis identified — targeted, not estate-wide.",
    requires: "A retirement date for whatever the modernised equipment replaces, not just an installation date for the new equipment.",
    doesNotFix: "The governance gap. A modernised network with no criteria for the next expansion decision recreates the same exposure within a few years.",
    measurement: "Metered baseline power at the modernised sites against last year's figure, over the same declared boundary.",
  },
  {
    id: "qualify",
    n: 3,
    label: "Prioritise IoT and 5G applications by real benefit, energy demand and lifecycle impact",
    changes: "The order proposals are approved in — a qualifier applied before deployment, not a review after the fact.",
    requires: "Criteria from lever 1 to qualify against, and the discipline to say no to a use case that does not clear them.",
    doesNotFix: "Devices or radios already installed under the old, unqualified process.",
    measurement: "The proportion of new IoT and 5G proposals that can name an evidenced requirement before approval, tracked quarter over quarter.",
  },
  {
    id: "data",
    n: 4,
    label: "Limit unnecessary data streams and focus on meaningful data use",
    changes: "Which data is collected and for how long — event-driven transmission over polling, and a named consumer for every stream that continues.",
    requires: "An owner per stream who can say which decision it feeds; a stream with no such owner is a candidate for switching off.",
    doesNotFix: "The volume already generated by devices and radios approved before this lever was pulled — it stops the flow adding to further.",
    measurement: "Data volume per active data-consuming decision, not data volume alone — a rising total with a rising number of decisions it serves is a different finding than a rising total with a flat one.",
  },
];

export const LEVER_INTRO =
  "Four levers, opened one at a time — self-paced, nothing here is locked. For each: what it changes, what it requires, what it deliberately does not fix, and how you would know it worked.";

// ---------------------------------------------------------------------------
// The section
// ---------------------------------------------------------------------------

export const D_LEVERS: MaterialSection<MaterialSectionId> = {
  id: "levers",
  code: "D",
  n: 4,
  icon: "blueprint",
  kicker: "D · Four moves, in the order that makes the others work",
  title: "The four biggest levers",
  standfirst: "One of these four makes the other three possible. The other three do not make it unnecessary.",
  minutes: 12,
  definition:
    "Four levers address NetSphere's exposure across the six dimensions: a governance framework for connected infrastructure, targeted network modernisation, benefit-based prioritisation of IoT and 5G, and discipline over data streams. Each changes something specific, requires a precondition, and deliberately leaves something unfixed.",
  insight:
    "The four are not interchangeable and not independent. Levers two through four each work better, and in some cases only work at all, once lever one exists — a qualifier for 5G use cases needs criteria to qualify against; a data-stream owner needs a framework that makes ownership someone's job rather than a favour. That dependency is the reasoning behind section E's prioritised choice, not an assertion made there for the first time.",
  takeaway:
    "For any lever you consider funding, state its measurement before you fund it. A lever with no stated evidence test is a hope, and every one of the four above has one written into it precisely so that 'it worked' or 'it did not' will be a checkable claim rather than an impression.",
  body: [],
  reasoning: [
    "In the Vertex task's decision-logic section, the criterion 'controllability' asks exactly the 'how would you know it worked' question these four levers each answer — reuse the discipline, not the specific numbers.",
    "Lever 1 is what section E recommends first for NetSphere. Read levers 2–4 as what it unlocks, not as competing alternatives to it.",
  ],
  callout: {
    label: "The dependency to notice",
    text: "Levers 2, 3 and 4 each work better once lever 1 exists. That is the argument for sequencing, not a coincidence of the list order.",
  },
  references: [
    {
      label: "Load-adaptive operation and legacy sunset",
      detail: "The specific technical levers lever 2 draws on — carrier and cell shutdown at low load, and retiring rather than stacking a generation.",
    },
  ],
};
